#!/usr/bin/env node

// Adds `description` to each function entry in top50_by_count.json.
// If `description` already exists, leave it as-is.
// Otherwise, generate a short description based on the function name and category.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const INPUT = path.join(ROOT, 'top50_by_count.json');

// Map of function names to descriptions
const descriptions = {
  "SQLExecute": "Executes a SQL command and returns the result as an SSLValue.",
  "Empty": "Checks if the given value is empty or null.",
  "DoProc": "Executes a stored procedure with the provided arguments.",
  "Len": "Returns the length of the input string.",
  "LimsString": "Converts the input value to a string representation.",
  "ExecFunction": "Executes a function by name with given parameters.",
  "usrmes": "Displays a user message with two arguments.",
  "Upper": "Converts the input string to uppercase.",
  "aadd": "Adds an element to the end of an array.",
  "Chr": "Returns the character corresponding to the given ASCII code.",
  "AllTrim": "Removes all leading and trailing whitespace from the string.",
  "RunSQL": "Executes a SQL command without returning data.",
  "SubStr": "Extracts a substring from the source string.",
  "Now": "Returns the current date and time.",
  "GetSetting": "Retrieves the value of a system setting by name.",
  "Left": "Returns the leftmost characters of the string.",
  "Val": "Converts a string to a numeric value.",
  "LSearch": "Performs a search query on the database.",
  "extractcol": "Extracts a column from a 2D array.",
  "At": "Finds the position of a substring within a string.",
  "Trim": "Removes leading and trailing whitespace from the string.",
  "Max": "Returns the maximum of two values.",
  "Time": "Returns the current time as a string.",
  "IIf": "Returns one of two values based on a condition.",
  "StrTran": "Replaces occurrences of a substring in a string.",
  "CreateUdObject": "Creates a user-defined object with arguments.",
  "RaiseError": "Raises an error with message, location, and code.",
  "Today": "Returns the current date.",
  "GetDataset": "Retrieves a dataset from a data source.",
  "buildstring": "Builds a string from array elements with a delimiter.",
  "Str": "Formats a number as a string with specified length and decimals.",
  "EndLimsTransaction": "Ends a LIMS database transaction.",
  "Replace": "Replaces all occurrences of a substring in a string.",
  "FileSupport": "Performs file operations based on the request type.",
  "LimsNETConnect": "Connects to a .NET assembly and type.",
  "Right": "Returns the rightmost characters of the string.",
  "GetDataSetXMLFromArray": "Converts an array to XML dataset format.",
  "LimsTypeEx": "Returns the extended type information of a value.",
  "GetLastSSLError": "Retrieves the last SSL error that occurred.",
  "BuildStringForIn": "Builds a comma-separated string for SQL IN clause.",
  "LimsTime": "Returns the current time in LIMS format.",
  "buildarray": "Builds an array from a string with delimiters.",
  "BeginLimsTransaction": "Begins a LIMS database transaction.",
  "getregion": "Retrieves a region from a string based on delimiters.",
  "ascan": "Scans an array for a value and returns its index.",
  "LimsSetCounter": "Sets a counter value in the database.",
  "Directory": "Lists files in a directory matching a pattern.",
  "ToXml": "Converts a value to XML string.",
  "LimsRecordsAffected": "Returns the number of records affected by the last SQL operation.",
  "LimsSqlConnect": "Connects to a SQL database by friendly name.",
  "WriteText": "Writes text to a file.",
  "Year": "Extracts the year from a date.",
  "LimsSqlDisconnect": "Disconnects from a SQL database.",
  "arraycalc": "Performs calculations on array elements.",
  "ReturnLastSQLError": "Returns the last SQL error.",
  "Min": "Returns the minimum of two values.",
  "Asc": "Returns the ASCII code of the first character in a string.",
  "StrZero": "Formats a number as a zero-padded string.",
  "IsTable": "Checks if a table exists in the database.",
  "Lower": "Converts the input string to lowercase.",
  "CreateGUID": "Generates a new globally unique identifier.",
  "LSelect1": "Executes a SELECT query and returns results as array.",
  "LimsType": "Returns the type information of a value.",
  "LIMSDate": "Formats a date according to a specified format.",
  "FromXml": "Converts an XML string to a value.",
  "LKill": "Kills a variable or session.",
  "GetDataSetWithSchemaFromSelect": "Retrieves dataset with schema from SELECT.",
  "GetFromSession": "Retrieves a value from the session.",
  "Nothing": "Checks if a value is null or nothing.",
  "ShowSqlErrors": "Toggles display of SQL errors.",
  "alen": "Returns the length of an array.",
  "SubmitToBatch": "Submits a code block to batch processing.",
  "Integer": "Truncates a decimal to an integer.",
  "DosSupport": "Provides DOS-style directory listing.",
  "ReadText": "Reads text from a file.",
  "ValidateNumeric": "Validates if a string represents a number.",
  "PrmCount": "Returns the number of parameters.",
  "ascanexact": "Scans array for exact value match.",
  "Day": "Extracts the day from a date.",
  "Rat": "Finds the last occurrence of a substring.",
  "Month": "Extracts the month from a date.",
  "Seconds": "Returns the current seconds since midnight.",
  "Second": "Extracts the second from a date.",
  "arraynew": "Creates a new multi-dimensional array.",
  "GetDataSetEx": "Retrieves dataset with extended options.",
  "AddToSession": "Adds a value to the session.",
  "execudf": "Executes a user-defined function.",
  "DToS": "Converts a date to string.",
  "LTrim": "Removes leading whitespace from a string.",
  "LSelect": "Executes a SELECT query with field list.",
  "GetLastSQLError": "Returns the last SQL error.",
  "BRANCH": "Branching logic (placeholder).",
  "lWait": "Waits for a specified number of seconds.",
  "GetDataSetFromArray": "Converts array to dataset format.",
  "DateAdd": "Adds a time interval to a date.",
  "FormatErrorMessage": "Formats an error message.",
  "AddProperty": "Adds a property to an object.",
  "DateDiff": "Calculates the difference between two dates.",
  "GetDataSetXMLFromSelect": "Retrieves XML dataset from SELECT.",
  "GetDataSetFromArrayEx": "Extended array to dataset conversion.",
  "DecryptData": "Decrypts data using a password.",
  "Round": "Rounds a number to specified digits.",
  "IsNumeric": "Checks if a value is numeric.",
  "Abs": "Returns the absolute value of a number.",
  "Hour": "Extracts the hour from a date.",
  "IgnoreSqlErrors": "Toggles ignoring of SQL errors.",
  "Replicate": "Repeats a string a specified number of times.",
  "LSelectC": "Executes SELECT with caching.",
  "DateToString": "Converts date to string with format.",
  "RunDS": "Runs a data source query.",
  "Break": "Breaks execution flow.",
  "Minute": "Extracts the minute from a date.",
  "LimsAt": "Finds substring position with offset.",
  "MatFunc": "Performs mathematical functions.",
  "aeval": "Evaluates a code block for each array element.",
  "buildstring2": "Builds string from array with line and column delimiters.",
  "LimsNETCast": "Casts a value to a .NET type.",
  "MimeDecode": "Decodes MIME-encoded data.",
  "LCase": "Conditional lowercase conversion.",
  "LimsExec": "Executes an external application.",
  "StationName": "Returns the workstation name.",
  "StdRound": "Rounds to standard significant figures.",
  "ToJson": "Converts a value to JSON string.",
  "delarray": "Deletes an element from an array.",
  "SigFig": "Formats to significant figures.",
  "CToD": "Converts string to date.",
  "buildarray2": "Builds array from string with advanced delimiters.",
  "GetInternal": "Retrieves internal property of an object.",
  "LimsCleanup": "Performs cleanup operations.",
  "StrSrch": "Searches for substring with options.",
  "DocGetErrorMessage": "Retrieves Documentum error message.",
  "IsDefined": "Checks if a variable is defined.",
  "UpdLong": "Updates long data in database.",
  "EncryptData": "Encrypts data with password and algorithm.",
  "IsGuid": "Checks if a string is a valid GUID.",
  "SetInternal": "Sets internal property of an object.",
  "HashData": "Hashes data with specified algorithm.",
  "SendLimsEmail": "Sends an email via LIMS.",
  "ChkPassword": "Checks user password.",
  "DateFormat": "Sets the date format.",
  "lDir": "Lists directory contents.",
  "StringToDate": "Converts string to date with format.",
  "GetConnectionByName": "Retrieves database connection by name.",
  "DateFromString": "Parses date from string with options.",
  "ErrorMes": "Displays an error message.",
  "TraceOn": "Enables tracing.",
  "RetrieveLong": "Retrieves long data from database.",
  "HasProperty": "Checks if an object has a property.",
  "SendToOutbox": "Sends email to outbox.",
  "GetByName": "Retrieves value by name.",
  "GetSettings": "Retrieves multiple settings.",
  "SortArray": "Sorts an array.",
  "DocCommandFailed": "Checks if Documentum command failed.",
  "CMonth": "Returns month name from date.",
  "GetLogsFolder": "Returns the logs folder path.",
  "LPrint": "Prints to LIMS output.",
  "DToC": "Converts date to string.",
  "ServerStartOfDay": "Returns server start of day.",
  "GetUserData": "Retrieves user data.",
  "FormatSqlErrorMessage": "Formats SQL error message.",
  "Rand": "Generates a random number.",
  "ClientStartOfDay": "Returns client start of day.",
  "eval": "Evaluates an expression.",
  "ResetApplication": "Resets the application state.",
  "DetectSqlInjections": "Toggles SQL injection detection.",
  "ClientEndOfDay": "Returns client end of day.",
  "GetInternalC": "Retrieves internal collection property.",
  "IsProductionModeOn": "Checks if production mode is on.",
  "limsoleconnect": "Connects to LIMS OLE.",
  "RunApp": "Runs an external application.",
  "Sqrt": "Returns the square root of a number.",
  "DateFromNumbers": "Creates date from numeric components.",
  "FromJson": "Converts JSON string to value.",
  "getinlinecode": "Retrieves inline code.",
  "JDay": "Returns Julian day number.",
  "SetSqlTimeout": "Sets SQL timeout.",
  "endlimsoleconnect": "Ends LIMS OLE connection.",
  "HtmlEncode": "Encodes string for HTML.",
  "InfoMes": "Displays an info message.",
  "SetAmPm": "Sets AM/PM display.",
  "WriteBytesBase64": "Writes base64 data to file.",
  "ArrayToTVP": "Converts array to table-valued parameter.",
  "ReadBytesBase64": "Reads file as base64 string.",
  "CreateZip": "Creates a ZIP archive.",
  "DocSearchUsingDql": "Searches Documentum using DQL.",
  "DOW": "Returns day of week.",
  "ExtractZip": "Extracts a ZIP archive."
};

function main() {
  const raw = fs.readFileSync(INPUT, 'utf8');
  const data = JSON.parse(raw);

  if (!data || !Array.isArray(data.functions)) {
    console.error('Invalid top50_by_count.json: missing functions array');
    process.exit(1);
  }

  let updated = 0;

  for (const fn of data.functions) {
    if (fn.description) continue; // respect existing

    const desc = descriptions[fn.name];
    if (desc) {
      fn.description = desc;
      updated++;
    }
  }

  fs.writeFileSync(INPUT, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`Added description to ${updated} functions.`);
}

if (require.main === module) {
  main();
}